version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Fase de instalación..."
  build:
    commands:
      - echo "Fase de construcción iniciada en `date`"
      # CODEBUILD_SRC_DIR es la variable de entorno que apunta al código fuente
      - echo "Directorio fuente: $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - echo "Contenido del directorio fuente:"
      - ls -la
      - echo "Empaquetando el código Lambda..."
      # Zipeamos el archivo desde dentro del directorio fuente
      - zip lambda_function.zip lambda_function.py
  post_build:
    commands:
      - echo "Fase de construcción completada en `date`"

artifacts:
  files:
    # Importante: Ahora especificamos la ruta RELATIVA al directorio fuente
    - lambda_function.zip