version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Fase de instalación..."
  build:
    commands:
      - echo "Fase de construcción iniciada en `date`"
      - echo "Contenido del directorio actual antes de zip:"
      - ls -la
      - echo "Empaquetando el código Lambda sin rutas..."
      # Usamos -j para junk paths (ignorar directorios)
      - zip -j lambda_function.zip lambda_function.py
  post_build:
    commands:
      - echo "Fase de construcción completada en `date`"

# SIN sección artifacts